### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by IsaccBarker** [zcalusic/sysinfo#17]
Hello. The description of this repo says %100 pure Go, but there is some assembly.

**Comment by zcalusic** [comment]
Hello @IsaccBarker and thanks for stopping by!

I gave it a good (several months good :smile:) thought and concluded that you might be right.

So, today is the day I will be removing word "pure" everywhere from the project. :smile:

P.S. If anybody can help with getting CPUID info without using assembly, I'd be more than happy to revert the commit that will follow up.
