### ISSUE TITLE
Stray os.Exit(0) call at end of func getSetMachineID

### ISSUE THREAD

**Issue by bediger4000** [zcalusic/sysinfo#19]
File node.go, func getSetMachineID - that function ends up calling os.Exit(0) under  the  circumstance where neither /etc/machine-id or the dbus machine-id exists. This seems incorrect.

**Comment by zcalusic** [comment]
Hello @bediger4000 and thanks for stopping by!

Gosh, that seems like a leftover from some debugging session, very good catch!

I'll fix it in a bit...

I guess nowadays people mostly do have machines with proper machine-id, 'cause it took so long to notice this "hidden gem". :smile:
