### ISSUE TITLE
Error on armv7 architecture

### ISSUE THREAD

**Issue by blaspix-tech** [zcalusic/sysinfo#26]
Hello,

This program crashes if I run the program on armv7l architecture.
Here is the error stack trace:
```
unexpected fault address 0x0
fatal error: fault
[signal SIGBUS: bus error code=0x3 addr=0x0 pc=0x12f58]
goroutine 1 [running]:
runtime.throw(0x473c24, 0x5)
        /usr/local/go/src/runtime/panic.go:1116 +0x5c fp=0xc3ec2c sp=0xc3ec18 pc=0x46804
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:714 +0x378 fp=0xc3ec44 sp=0xc3ec2c pc=0x5df14
memeqbody()
        /usr/local/go/src/internal/bytealg/equal_arm.s:89 +0x88 fp=0xc3ec48 sp=0xc3ec48 pc=0x12f58
bytes.Equal(...)
        /usr/local/go/src/bytes/bytes.go:20
github.com/zcalusic/sysinfo.getStructureTableAddress(0xc90378, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/networkd/src/github.com/zcalusic/sysinfo/memory.go:111 +0x268 fp=0xc3ecac sp=0xc3ec48 pc=0x16ded4
github.com/zcalusic/sysinfo.getStructureTable(0x0, 0x0, 0x0, 0x0, 0x0)
        /go/networkd/src/github.com/zcalusic/sysinfo/memory.go:139 +0x2a4 fp=0xc3ed04 sp=0xc3ecac pc=0x16e29c
github.com/zcalusic/sysinfo.(*SysInfo).getMemoryInfo(0xccc000)
        /go/networkd/src/github.com/zcalusic/sysinfo/memory.go:155 +0x2c fp=0xc3ee58 sp=0xc3ed04 pc=0x16e370
github.com/zcalusic/sysinfo.(*SysInfo).GetSysInfo(0xccc000)
        /go/networkd/src/github.com/zcalusic/sysinfo/sysinfo.go:36 +0xa0 fp=0xc3ee84 sp=0xc3ee58 pc=0x171538
main.GetSysInfo(0x0, 0xc3ef20)
```

**Comment by blaspix-tech** [comment]
The error seems to come from the memory package.

**Comment by zcalusic** [comment]
Hello @blaspix-tech,

Unfortunately, I don't have access to armv7 architecture, so can't investigate much further.

Still, it's pretty obvious that it panics trying to search through /dev/mem device, looking for DMI/SMBIOS. Which is a pretty complex part, but unfortunately the only way I found to detect the exact amount of RAM installed. Anything else, i.e. reading from /proc/meminfo or similar, just an approximation...

It not nice that it panics, still, if you could run dmidecode utility as superuser on that architecture, and see what it outputs? If it doesn't show info about Memory Devices, unfortunately it's not available at all on that platform.
