### ISSUE TITLE
Couldn't compile on Mac OS

### ISSUE THREAD

**Issue by agareev** [zcalusic/sysinfo#3]
I have a problem with build sysinfo on my OSX Laptop.

`../sysinfo/kernel.go:24: undefined: syscall.Utsname
../sysinfo/kernel.go:25: undefined: syscall.Uname`

**Comment by zcalusic** [comment]
Huh, tough luck. I'm afraid this library is quite Linux specific, as specified in the README. I'm not even sure it could be ported to OSX at all, due to usage of quite low level Linux stuff.

**Comment by agareev** [comment]
Ok, I see.

We use this library for collect information about many our servers. And I want to develop a client which based on your lib. But I can't :)
