### ISSUE TITLE
Version semantics

### ISSUE THREAD

**Issue by Danile71** [zcalusic/sysinfo#33]
Hi! Thanks for this project!
Can you create release tags? v0.9.5?
go mod tidy
```github.com/zcalusic/sysinfo v0.0.0-20210905121133-6fa2f969a900```
Maybe it will be better?
```github.com/zcalusic/sysinfo v0.9.5```

**Comment by henri9813** [comment]
+1, can you make an official release please ?

**Comment by ashokmariyala** [comment]
+1, Could you please make an official release version?
Thanks in advance.

**Comment by zcalusic** [comment]
By popular demand... :smiley: we now have tags. I tagged all versions from the current 0.9.5 back to 0.9.1

Let me know if this works for you.

**Comment by Danile71** [comment]
Thanks! It works)

**Comment by zcalusic** [comment]
Version 1.0.0 just released, I think this issue can be closed now.
